### ISSUE TITLE
Aggregate Entitlements does not work

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/typescript-sdk#36]
The api-specs says that the csvFile is required but the description says otherwise.
![image](https://github.com/sailpoint-oss/typescript-sdk/assets/82362286/a6493237-bdc1-4b07-b197-8ccd5953b75e)
Also beware that the description is explaining a "complex" behavior for the Content-Type header.

As of now (version 1.3.3), when trying to use `importEntitlements`, `csvFile` is required.
But when set to `null`, we get the error:

```
RequiredError: Required parameter csvFile was null or undefined when calling importEntitlements.
```

Code example to reproduce:

```
const api = new EntitlementsBetaApi(apiConfig);
		const response = await api.importEntitlements({
			id: sourceID,
			csvFile: null
		})
```

**Comment by tyler-mairose-sp** [comment]
Hey @yannick-beot-sp, we noticed this as well and made some updates to the specifications to correct this.

It is fixed in https://github.com/sailpoint-oss/typescript-sdk/commit/050062b39661a8bdf71acaa0b721453c8a6df5d4 and released in https://github.com/sailpoint-oss/typescript-sdk/releases/tag/v1.3.4

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/identitynow-extensions-for-visual-studio-code/5983/122
